CREATE TABLE IF NOT EXISTS mpa
(
    mpa_id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mpa_name VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS films
(
    film_id      int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_name    VARCHAR(155) NOT NULL,
    description  VARCHAR(200) NOT NULL,
    release_date DATE         NOT NULL,
    duration     int          NOT NULL,
    mpa_id       int REFERENCES mpa (mpa_id)
);



CREATE TABLE IF NOT EXISTS genres
(
    genre_id   INTEGER GENERATED by default AS IDENTITY PRIMARY KEY,
    genre_name VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS film_genres
(
    film_id  int REFERENCES films (film_id),
    genre_id int REFERENCES genres (genre_id),

    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS users
(
    user_id  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(255) NOT NULL,
    login    VARCHAR(255) NOT NULL,
    name     VARCHAR(255),
    birthday DATE
);
CREATE UNIQUE INDEX IF NOT EXISTS user_email_index ON users (email);
CREATE UNIQUE INDEX IF NOT EXISTS user_login_index ON users (login);

CREATE TABLE IF NOT EXISTS friendship
(
    user_id   int REFERENCES users (user_id),
    friend_id int REFERENCES users (user_id),
    PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS likes
(
    film_id int REFERENCES films (film_id),
    user_id int REFERENCES users (user_id),

    PRIMARY KEY (film_id, user_id)
);
